{
 "title": "RRI",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Stevec preklopov",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PresaStevec\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data1 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fromS7_mqtt\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rt1_ch2\" or r[\"_field\"] == \"rtd1_ch0\" or r[\"_field\"] == \"rtd1_ch1\" or r[\"_field\"] == \"rtd1_ch3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\ndata2 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura okolice\" or r[\"_field\"] == \"Temperatura orodja 1\" or r[\"_field\"] == \"Temperatura orodja 2\" or r[\"_field\"] == \"Rezerva\" or r[\"_field\"] == \"Temperatura okolice RTD\" or  r[\"_field\"] == \"Egasi_Temperatura\" or  r[\"_field\"] == \"Temperatura ohisje aktuator RTD\"  or  r[\"_field\"] == \"Temperatura orodja RTD\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nunion(tables: [data1, data2])\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Hitrost stiskalnice",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PresaHitrost\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data1 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fromS7_mqtt\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"M1_temp\" or r[\"_field\"] == \"M2_temp\" or r[\"_field\"] == \"M3_temp\" or r[\"_field\"] == \"M4_temp\" or r[\"_field\"] == \"M5_temp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\ndata2 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"M1_temp\" or  r[\"_field\"] == \"M2_temp\"  or r[\"_field\"] == \"M3_temp\" or r[\"_field\"] == \"M4_temp\" or r[\"_field\"] == \"M5_temp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nunion(tables: [data1, data2])\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "data1 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fromS7_mqtt\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"M1_temp\" or r[\"_field\"] == \"M2_temp\" or r[\"_field\"] == \"M3_temp\" or r[\"_field\"] == \"M4_temp\" or r[\"_field\"] == \"M5_temp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\ndata2 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"M1_temp\" or  r[\"_field\"] == \"M2_temp\"  or r[\"_field\"] == \"M3_temp\" or r[\"_field\"] == \"M4_temp\" or r[\"_field\"] == \"M5_temp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nunion(tables: [data1, data2])\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data1 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fromS7_mqtt\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"M1_temp\" or r[\"_field\"] == \"M2_temp\" or r[\"_field\"] == \"M3_temp\" or r[\"_field\"] == \"M4_temp\" or r[\"_field\"] == \"M5_temp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\ndata2 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"M1_temp\" or  r[\"_field\"] == \"M2_temp\"  or r[\"_field\"] == \"M3_temp\" or r[\"_field\"] == \"M4_temp\" or r[\"_field\"] == \"M5_temp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nunion(tables: [data1, data2])\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Hitrost stiskalnice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PresaHitrost\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Maksimalna sila",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi1_maxForce\")\r\n  |> aggregateWindow(every: 60s, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Maksimalna sila",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi1_maxForce\")\r\n  |> aggregateWindow(every: 60s, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Maksimalna sila",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi1_maxForce\")\r\n  |> aggregateWindow(every: 60s, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Maksimalna sila",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi1_maxForce\")\r\n  |> aggregateWindow(every: 60s, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Maksimalna sila",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi1_maxForce\")\r\n  |> aggregateWindow(every: 60s, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Minimalna sila",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi1_minForce\")\r\n  |> aggregateWindow(every: 60s, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Minimalna sila",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi1_minForce\")\r\n  |> aggregateWindow(every: 60s, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Minimalna sila",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi1_minForce\")\r\n  |> aggregateWindow(every: 60s, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Minimalna sila",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi1_minForce\")\r\n  |> aggregateWindow(every: 60s, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Minimalna sila",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi1_minForce\")\r\n  |> aggregateWindow(every: 60s, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data1 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fromS7_mqtt\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rt1_ch2\" or r[\"_field\"] == \"rtd1_ch0\" or r[\"_field\"] == \"rtd1_ch1\" or r[\"_field\"] == \"rtd1_ch3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\ndata2 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura okolice\" or r[\"_field\"] == \"Temperatura orodja 1\" or r[\"_field\"] == \"Temperatura orodja 2\" or r[\"_field\"] == \"Rezerva\" or r[\"_field\"] == \"Temperatura okolice RTD\" or  r[\"_field\"] == \"Egasi_Temperatura\" or  r[\"_field\"] == \"Temperatura ohisje aktuator RTD\"  or  r[\"_field\"] == \"Temperatura orodja RTD\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nunion(tables: [data1, data2])\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Maksimalna sila",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi1_maxForce\" or r[\"_field\"] == \"Egasi1_minForce\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "data1 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fromS7_mqtt\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rt1_ch2\" or r[\"_field\"] == \"rtd1_ch0\" or r[\"_field\"] == \"rtd1_ch1\" or r[\"_field\"] == \"rtd1_ch3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\ndata2 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura okolice\" or r[\"_field\"] == \"Temperatura orodja 1\" or r[\"_field\"] == \"Temperatura orodja 2\" or r[\"_field\"] == \"Rezerva\" or r[\"_field\"] == \"Temperatura okolice RTD\" or  r[\"_field\"] == \"Egasi_Temperatura\"  or  r[\"_field\"] == \"Temperatura ohisje aktuator RTD\"  or  r[\"_field\"] == \"Temperatura orodja RTD\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nunion(tables: [data1, data2])\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Projekt RRI / DD",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 44 },
   "options": {
    "content": "<a href=\"https://freeimage.host/i/d60cEpn\"><img src=\"https://iili.io/d60cEpn.md.jpg\" alt=\"d60cEpn.md.jpg\" border=\"0\"></a>"
   }
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 44 },
   "targets": [
    {
     "query": "data1 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fromS7_mqtt\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rt1_ch2\" or r[\"_field\"] == \"rtd1_ch0\" or r[\"_field\"] == \"rtd1_ch1\" or r[\"_field\"] == \"rtd1_ch3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\ndata2 = from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura okolice\" or r[\"_field\"] == \"Temperatura orodja 1\" or r[\"_field\"] == \"Temperatura orodja 2\" or r[\"_field\"] == \"Rezerva\" or r[\"_field\"] == \"Temperatura okolice RTD\" or  r[\"_field\"] == \"Egasi_Temperatura\"  or  r[\"_field\"] == \"Temperatura ohisje aktuator RTD\"  or  r[\"_field\"] == \"Temperatura orodja RTD\" or r[\"_field\"] == \"PresaStevec\" or r[\"_field\"] == \"PresaHitrost\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nunion(tables: [data1, data2])\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Temperatura - EGASI",
   "type": "stat",
   "description": "temperatura v aktuatorju",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temeratura okolice ",
     "measurement": "Orodje_temperatura",
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Egasi_Temperatura\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "Temperatura okolice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RRI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TestiranjeAktuatorja_13092024\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura okolice\" or r[\"_field\"] == \"Temperatura orodja 1\" or r[\"_field\"] == \"Temperatura orodja 2\" or r[\"_field\"] == \"Rezerva\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}